package GlobalComponents;

import GraphicsController.Graphics;

public class SetAllInvisible {
	
	public SetAllInvisible(Graphics graphics, String source){
		
		if(source == "mainmenu"){
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.menu.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}

		if(source == "character"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.menu.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.help.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		if(source == "login"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.menu.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.help.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		if(source == "diff"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
	    	graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.help.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		if(source == "selector"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.help.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		if(source == "creator"){
			
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.help.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		if(source == "game"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.loginPanel.setVisible(false);
	    	graphics.characterPanel.setVisible(false);
	    	graphics.optionsPanel.setVisible(false);
	    	graphics.load.setVisible(false);
	    	graphics.help.setVisible(false);
	    	graphics.helpPanel.setVisible(false);
	    	graphics.choose.setVisible(false);
	    	graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		if(source == "options"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.help.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.multiplier.setVisible(false);
		}
		
		if(source == "help"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.menu.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.help.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		if(source == "intro"){
			graphics.play.setVisible(false);
	    	graphics.worldcreater.setVisible(false);
	    	graphics.options.setVisible(false);
	    	graphics.exit.setVisible(false);
			graphics.red.setVisible(false);
	    	graphics.gray.setVisible(false);
	    	graphics.white.setVisible(false);
	    	graphics.save.setVisible(false);
	    	graphics.menu.setVisible(false);
	    	graphics.panelParent.setVisible(false);
	    	graphics.easy.setVisible(false);
	    	graphics.medium.setVisible(false);
	    	graphics.hard.setVisible(false);
	    	graphics.turret1.setVisible(false);
	    	graphics.turret2.setVisible(false);
	    	graphics.nextwave.setVisible(false);
	        graphics.pause.setVisible(false);
	        graphics.sell.setVisible(false);
			graphics.upgrade.setVisible(false);
			graphics.nearest.setVisible(false);
			graphics.farthest.setVisible(false);
			graphics.highest.setVisible(false);
			graphics.lowest.setVisible(false);
			graphics.loginPanel.setVisible(false);
			graphics.characterPanel.setVisible(false);
			graphics.optionsPanel.setVisible(false);
			graphics.save2.setVisible(false);
			graphics.load.setVisible(false);
			graphics.help.setVisible(false);
			graphics.helpPanel.setVisible(false);
			graphics.choose.setVisible(false);
			graphics.customNormalCreep.setVisible(false);
			graphics.customFastCreep.setVisible(false);
			graphics.customBossCreep.setVisible(false);
			graphics.customFlyingCreep.setVisible(false);
			graphics.customNormalTower.setVisible(false);
			graphics.customSplashTower.setVisible(false);
			graphics.multiplier.setVisible(false);
			graphics.highscores.setVisible(false);
		}
		
		
	}

}

